apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: nfs.csi.k8s.io
metadata:
  name: synology-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  server: 192.168.10.3
  path: /volume4/k8s
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
