---
- name: Create .kube directory
  file:
    path: "/home/{{ ansible_env.SUDO_USER + '/.kube'}}"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: "u=rwx,g=rx,o="

- name: Copy kubeconfig file to user's .kube-directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_env.SUDO_USER + '/.kube/config'}}"
    remote_src: yes
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: "u=rw,g=,o="

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link