apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/kaidobit/homelab
    targetRevision: main
    path: services/cluster-storage
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m