apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.13.12
      helm:
        releaseName: metallb
#        valueFiles:
#          - $repo/services/metallb/values.yml
    - repoURL: ssh://git@github.com/kaidobit/homelab
      plugin:
        name: argocd-vault-plugin
      targetRevision: main
      path: services/metallb
#      ref: repo
  destination:
    name: in-cluster
    namespace: metallb
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m