---
- name: Copy k3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check k3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  no_log: True

- name: Wait for node-token
  wait_for:
    path: "{{ k3s_server_location }}/server/node-token"

- name: Change file access of node-token-file
  file:
    path: "{{ k3s_server_location }}/server/node-token"
    mode: "g+rx,o+rx"

- name: Change file access of master-token-file
  file:
    path: "{{ k3s_server_location }}/server/token"
    mode: "g+rx,o+rx"

- name: Get node-token on main-master
  command: "cat {{ k3s_server_location }}/server/node-token"
  register: node_token
  no_log: True

- name: Write node-token to HCP vault
  community.hashi_vault.vault_write:
    url: "{{ vault_hostname }}"
    path: "k8s/cluster-token"
    data:
      token: "{{ node_token.stdout }}"
    auth_method: token
    token: "{{ vault_auth_token }}"
  no_log: True
