apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: iot
    namespace: metallb
spec:
    addresses:
        - ENC[AES256_GCM,data:lShksLs2QLx0bqIBt/u23gj+sR47iSH1,iv:k6BhwMtdLgVjTWcWyk4aScwSwTdFlp7OKfBv8woPUVU=,tag:jz1TP50yZLLL/91E9MhvEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://192.168.10.3:8200
          engine_path: sops
          key_name: homelab
          created_at: "2023-11-29T13:36:30Z"
          enc: vault:v1:LMOEG4N0QnIUG/ZLZejPItxnzcoDrxtmHRRjjNogNZpUE9haf4WNh6bf9/N5kCXjMNxwuxVep6kWYqr7
    age: []
    lastmodified: "2023-11-29T13:36:30Z"
    mac: ENC[AES256_GCM,data:PaYLThb3LuO48SC6DJuQ3TqISGhi779uqWyVLDIhbcgh3rFYmBP5kFAgU0JwS4X33S/or5kTu8d/GvnulW3SULcYh919e4+uQdFdRUX61agp8Wl8CYBecB11NoXoXgKL8TehZ7OuIyz9pUM2HBUXnlF8a9F3F4qxXRnBn+fe2Zg=,iv:bCXlXYgTBxkrYtWkFt2H6eElnyDHKzfKce/pjz0zbDk=,tag:7pcw1n3+iqDVBGAOn8u6sg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type|immutable)$
    version: 3.7.3
