version: '3.3'
services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5433:5432'
    image: ankane/pgvector:v0.5.0
volumes:
  postgres-data: