version: "3.7"

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    command: ["server", "/data"]
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - $MINIO_HOST_CONFIG_DIR_PATH:/root/.minio
      - $MINIO_HOST_DATA_DIR_PATH:/data
    networks:
      - minio
  minio-console:
    container_name: minio_console
    image: minio/console:v0.25.0
    environment:
      - CONSOLE_MINIO_SERVER=http://minio:9000
      - CONSOLE_PBKDF_PASSPHRASE=secret
      - CONSOLE_PBKDF_SALT=secret
    command: ["server"]
    restart: unless-stopped
    ports:
      - 9001:9090
    networks:
      - minio

networks:
  minio:

